# Generated by Django 4.2.7 on 2023-11-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('sub_head', models.CharField(max_length=70)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='picture')),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=12)),
            ],
        ),
    ]
